typography_spectrum: 0.357108891941607
color:
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
  brandStrength: 0.8002423266880214
  lightness: 0.2800089761149138
  saturation: 0.5981481762137264
  rhythmicContrast: 0.6229308545589447
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9496501937974244
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4dfbfbc2-0dbb-4849-b832-32474c6afa69.png
name: Fancy~Skateboards
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Instagram
    url: 'https://www.instagram.com/samworthisfancy/'
    type: external
  - name: Youtube
    url: 'https://www.youtube.com/channel/UCM7IIxrY4NLba0ttgh4JlxA'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6800d8f7-dff5-4797-9f2e-e0fe24cd5022.ico
title: gnar shiek
description: '#fancyskateboards'
purpose: []
