typography_spectrum: 0.11168457311578095
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.6603500810451806
  lightness: 0.9492970865685493
  saturation: 0.9713022594805807
  rhythmicContrast: 0.7680255910381675
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3146991895046085
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Sam Worth
  email: samcworth@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4dfbfbc2-0dbb-4849-b832-32474c6afa69.png
name: FancySkateboards
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: '@samworthisfancy'
    url: 'https://www.instagram.com/samworthisfancy/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/513d79a7-fcde-44ad-bcae-f2ca1be8c4a8.png
title: Sam Worth's personal line of skateboards
description: '~gnar shiek e-commerce, videography and artwork~'
purpose: []
