typography_spectrum: 0.9132115310057998
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.1771321843843907
  lightness: 0.7973857957404107
  saturation: 0.7838045915123075
  rhythmicContrast: 0.10123543115332723
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1336053255945444
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Sam Worth
  email: samcworth@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4dfbfbc2-0dbb-4849-b832-32474c6afa69.png
name: FancySkateboards
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: '@samworthisfancy'
    url: 'https://www.instagram.com/samworthisfancy/'
    type: external
  - name: surfbirdstreet
    url: 'https://www.youtube.com/user/Surfbirdstreet'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/513d79a7-fcde-44ad-bcae-f2ca1be8c4a8.png
title: Sam Worth's personal skateboard line & blog
description: '~gnar shiek e-commerce, videography and artwork~'
purpose: []
